[2020-06-03 13:34:21,811] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_dag.csv_to_table 2020-06-03T07:51:04.028764+00:00 [queued]>
[2020-06-03 13:34:21,819] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_dag.csv_to_table 2020-06-03T07:51:04.028764+00:00 [queued]>
[2020-06-03 13:34:21,819] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 13:34:21,819] {taskinstance.py:880} INFO - Starting attempt 2 of 11
[2020-06-03 13:34:21,819] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 13:34:21,827] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): csv_to_table> on 2020-06-03T07:51:04.028764+00:00
[2020-06-03 13:34:21,829] {standard_task_runner.py:53} INFO - Started process 9659 to run task
[2020-06-03 13:34:21,863] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_dag.csv_to_table 2020-06-03T07:51:04.028764+00:00 [running]> nineleaps-ThinkPad-L470
[2020-06-03 13:34:21,871] {taskinstance.py:1145} ERROR - name 'yest_date' is not defined
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/covid_dag.py", line 40, in csv_to_table
    data = pd.read_csv('/home/nineleaps/Data/CovidData_' + yest_date.strftime("%d-%b-%y") + '.csv')
NameError: name 'yest_date' is not defined
[2020-06-03 13:34:21,872] {taskinstance.py:1168} INFO - Marking task as UP_FOR_RETRY
[2020-06-03 13:34:31,817] {logging_mixin.py:112} INFO - [2020-06-03 13:34:31,816] {local_task_job.py:103} INFO - Task exited with return code 1
