[2020-06-05 18:38:18,567] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T13:07:37.827947+00:00 [queued]>
[2020-06-05 18:38:18,575] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T13:07:37.827947+00:00 [queued]>
[2020-06-05 18:38:18,575] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 18:38:18,576] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-05 18:38:18,576] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 18:38:18,590] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): source_to_csv> on 2020-06-05T13:07:37.827947+00:00
[2020-06-05 18:38:18,594] {standard_task_runner.py:53} INFO - Started process 31602 to run task
[2020-06-05 18:38:18,628] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T13:07:37.827947+00:00 [running]> nineleaps-ThinkPad-L470
[2020-06-05 18:38:19,214] {logging_mixin.py:112} INFO - [2020-06-05 18:38:19,212] {covid_india_dag.py:50} ERROR - Http Error: 404 Client Error: Not Found for url: https://api.covid19india.org/states_daily.jso
[2020-06-05 18:38:28,579] {logging_mixin.py:112} INFO - [2020-06-05 18:38:28,578] {local_task_job.py:103} INFO - Task exited with return code 0
