[2020-06-05 13:24:56,454] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T07:54:04.304793+00:00 [queued]>
[2020-06-05 13:24:56,459] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T07:54:04.304793+00:00 [queued]>
[2020-06-05 13:24:56,460] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 13:24:56,460] {taskinstance.py:880} INFO - Starting attempt 1 of 2
[2020-06-05 13:24:56,460] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 13:24:56,468] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): source_to_csv> on 2020-06-05T07:54:04.304793+00:00
[2020-06-05 13:24:56,470] {standard_task_runner.py:53} INFO - Started process 4949 to run task
[2020-06-05 13:24:56,519] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T07:54:04.304793+00:00 [running]> nineleaps-ThinkPad-L470
[2020-06-05 13:24:57,429] {logging_mixin.py:112} INFO - [2020-06-05 13:24:57,427] {Covid_India_SampleDag.py:46} ERROR - HTTP Error.
[2020-06-05 13:25:06,454] {logging_mixin.py:112} INFO - [2020-06-05 13:25:06,453] {local_task_job.py:103} INFO - Task exited with return code 0
