[2020-06-05 17:14:37,981] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T11:42:28.674539+00:00 [queued]>
[2020-06-05 17:14:37,990] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T11:42:28.674539+00:00 [queued]>
[2020-06-05 17:14:37,990] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 17:14:37,991] {taskinstance.py:880} INFO - Starting attempt 2 of 2
[2020-06-05 17:14:37,991] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-05 17:14:37,998] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): source_to_csv> on 2020-06-05T11:42:28.674539+00:00
[2020-06-05 17:14:38,002] {standard_task_runner.py:53} INFO - Started process 24272 to run task
[2020-06-05 17:14:38,036] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_india_dag.source_to_csv 2020-06-05T11:42:28.674539+00:00 [running]> nineleaps-ThinkPad-L470
[2020-06-05 17:14:38,576] {logging_mixin.py:112} INFO - [2020-06-05 17:14:38,575] {Covid_India_SampleDag.py:48} ERROR - Http Error: 404 Client Error: Not Found for url: https://api.covid19india.org/states_daily.jso
[2020-06-05 17:14:47,986] {logging_mixin.py:112} INFO - [2020-06-05 17:14:47,985] {local_task_job.py:103} INFO - Task exited with return code 0
