[2020-06-03 18:07:06,804] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_dag.upload_percentage 2020-06-03T12:30:45.929313+00:00 [queued]>
[2020-06-03 18:07:06,812] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: covid_dag.upload_percentage 2020-06-03T12:30:45.929313+00:00 [queued]>
[2020-06-03 18:07:06,812] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 18:07:06,812] {taskinstance.py:880} INFO - Starting attempt 4 of 4
[2020-06-03 18:07:06,812] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 18:07:06,820] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): upload_percentage> on 2020-06-03T12:30:45.929313+00:00
[2020-06-03 18:07:06,822] {standard_task_runner.py:53} INFO - Started process 27037 to run task
[2020-06-03 18:07:06,855] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_dag.upload_percentage 2020-06-03T12:30:45.929313+00:00 [running]> nineleaps-ThinkPad-L470
[2020-06-03 18:07:10,730] {taskinstance.py:1145} ERROR - name 'csv' is not defined
Traceback (most recent call last):
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 983, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/home/nineleaps/.local/lib/python3.6/site-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/covid_dag.py", line 66, in upload_percentage
    reader_file = csv.reader(input_file)
NameError: name 'csv' is not defined
[2020-06-03 18:07:10,732] {taskinstance.py:1187} INFO - All retries failed; marking task as FAILED.dag_id=covid_dag, task_id=upload_percentage, execution_date=20200603T123045, start_date=20200603T123706, end_date=20200603T123710
[2020-06-03 18:07:16,802] {logging_mixin.py:112} INFO - [2020-06-03 18:07:16,801] {local_task_job.py:103} INFO - Task exited with return code 1
